// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjrnokxrxuwrmryicqig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcm5va3hyeHV3cm1yeWljcWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzUyOTcsImV4cCI6MjA1OTUxMTI5N30.j75L_vkHN2x4W6gQu_OB_RAYNpoeHbZrQbA2JfdY67E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);